### ISSUE TITLE
User Fotoğraf eklemediği halde fotoğrafı çekmeye çalışıyor

### ISSUE THREAD

**Issue by BTaskaya** [hakancelik96/coogger#10]
User Fotoğraf eklemediği halde fotoğrafı çekmeye çalışıyor

```
[03/Dec/2017 13:01:24] "GET /media/users/pp/pp-asdasdasd.jpg HTTP/1.1" 404 1820
[03/Dec/2017 13:01:24] "GET /media/users/pp/pp-asdasdasd.jpg HTTP/1.1" 404 1820
```
---

**Comment by hakancelik96** [comment]
bunun olmaması gerekiyordu hangi sayfaya girince foto çekiyor hepsindemi yoksa belirli bir sayfa mı ?

**Comment by BTaskaya** [comment]
Random yerlere girdim test amaçlı sonra logları inceledim.

**Comment by BTaskaya** [comment]
Sorun her sayfada oluşuyor. Sol üstteki profil kısmına dikkat ederseniz zaten broken image çekmeye çalıştığını fark edersiniz.
![image](https://user-images.githubusercontent.com/25110697/33524308-d847f5fc-d82b-11e7-8c52-29356f868754.png)

**Comment by hakancelik96** [comment]
hatanın sebebi https://github.com/hakancelik96/coogger/blob/super-coogger/cooggerapp/templates/home/header.html#L13 bu kısım foto varmı yok mu diye OtherInformationOfUsers modelinden bakması gerek ve eğer yoksa sitatic resim olan https://github.com/hakancelik96/coogger/blob/super-coogger/cooggerapp/static/media/profil.png bunu çekmesi gerek ayarlarız bunuda

**Comment by BTaskaya** [comment]
Katılıyorum.

**Comment by BTaskaya** [comment]
Issue'yı aç istersen. 
![image](https://user-images.githubusercontent.com/25110697/33554984-d446cde0-d90f-11e7-9a22-5136f9bc8c08.png)

**Comment by hakancelik96** [comment]
sorunlar çözüldü diye umarak kapatıyorum :D
