### ISSUE TITLE
destek verenlerin belirtilmesi

### ISSUE THREAD

**Issue by hakancelik96** [hakancelik96/coogger#13]
destek verenlerin web sitede belirtilmesi için footer bölümünde katgıda bulunanlar adında bir adres verilmeli ve bu adres kısmında destek veren kişilerin bilgileri verdiği katkılar ve iletişim hesaplarının verilmesi gerek

**Comment by hakancelik96** [comment]
proje kısmına taşındı

**Comment by BTaskaya** [comment]
Readme'de de belirtelim mi?

**Comment by BTaskaya** [comment]
+ Projede statik olarak belirtmek için PyGithub modülünü kullanabiliriz. PyGithub ile anlık olarak contributerların listesini çekip fotoğraf + profil linklerini belirtebiliriz.
