### ISSUE TITLE
Var Olmayan Kullanıcıda HTTP 500 Hatası

### ISSUE THREAD

**Issue by BTaskaya** [hakancelik96/coogger#21]
Var olmayan bir kullanıcının adresine erişmeyi denersem HTTP 500 alıyorum , illa hata döndürcekseniz HTTP 404 döndürebilirsiniz fakat bence anasayfaya redirect edilip anasayfada bir alert kutusu ile istediği kullanıcının olmadığını belirtebilirsiniz.

![image](https://user-images.githubusercontent.com/25110697/34320528-521f2e0e-e80d-11e7-9a08-4dd5c659de54.png)

**Comment by hakancelik96** [comment]
aynen dediğin gibi yapılacak saol 😊🖐️

**Comment by hakancelik96** [comment]
yaptım o yüzden kapatıyorum
