### ISSUE TITLE
Okunma Sayısı Yazmıyor

### ISSUE THREAD

**Issue by BTaskaya** [hakancelik96/coogger#23]
![image](https://user-images.githubusercontent.com/25110697/34455420-081b97ba-ed90-11e7-8db0-6c089d33d6be.png)
Okunma Sayısı Yazmıyor

**Comment by hakancelik96** [comment]
This issue occurs after the 22nd line in the [detail.py](https://github.com/hakancelik96/coogger/blob/super-coogger/cooggerapp/views/detail.py)  file

**Comment by hakancelik96** [comment]
Bu sorunda çözüldü
