### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by BarisTutakli** [hakancelik96/coogger#4]
ı tried to change my user name .But ı received an error  message .Can you check it please?

**Comment by BTaskaya** [comment]
Can you send error log?

**Comment by hakancelik96** [comment]
Request Method: | POST
-- | --
http://www.coogger.com/settings/profile
1.11.5
UnboundLocalError
local variable 'form' referenced before assignment
/home/coogger/coogger/cooggerapp/views/csettings.py in profile, line 17
/usr/local/bin/uwsgi
3.5.2
['/var/www',  '.',  '',  '/var/www',  '/home/coogger/coogger/lanet/lib/python3.5',  '/home/coogger/coogger/lanet/lib/python3.5/plat-x86_64-linux-gnu',  '/home/coogger/coogger/lanet/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/coogger/coogger/lanet/lib/python3.5/site-packages',  '/home/coogger/coogger']



line 17 csettings.py form
