### ISSUE TITLE
urls.py için Importlar

### ISSUE THREAD

**Issue by BTaskaya** [hakancelik96/coogger#5]
Pep8'in Aynı modülün fonksiyonlarının import edilmesi hakkında ki [içeriği](https://www.python.org/dev/peps/pep-0008/#imports).

Bir örnek:
```python
from subprocess import Popen, PIPE
```
---
Djangonun Importlar hakkında ki [tutumu](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#imports).

```python
from django.http.response import (
    Http404, HttpResponse, HttpResponseNotAllowed, StreamingHttpResponse,
    cookie,
)
```

Ayrıca Django Coding Style sayfasına göre:

>Sort lines in each group alphabetically by the full module name.

---
URLS.py'daki importlar
```python
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import os
from .views import home
from .views import signup_or_login
from .views import detail
from .views import users
from .views import topics
from .views import tools
from .views import controls
from .views import explorer
from .views import csettings
```
---

**Comment by hakancelik96** [comment]
bundan haberim yoktu güzelmiş

**Comment by BTaskaya** [comment]
Kapanabilir.
